### ISSUE TITLE
Direction on the input audio file for the azerty keyboard

### ISSUE THREAD

**Issue by spacether** [Zulko/pianoputer#15]
Thank you for making this tool!
I am working on some updates to it at: https://github.com/spacether/pianoputer/tree/misc_improvements
What is the expected input note for the audio file for the azerty keyboard?
Should it be middle c, c4?
In the code I see that it makes 25 tones higher and lower than the input audio file.

**Comment by Zulko** [comment]
Hey! I don't think there is a definitive answer to this, I think the bowl sound is closest to an g4 or an a5, but if you had a lower-pitched sound you could always adapt the range (go from 15 tones lower to 35 tones higher, for instance).

Also keep in mind that the pitch-shifting algorithm used in these scripts is not state of the art (see the [blog post](http://zulko.github.io/blog/2014/03/29/soundstretching-and-pitch-shifting-in-python/) for more),and can create distorsions. I have succesfully used third-party sound stretchers in the past but I cant remember the names (Audacity or some related software that could be called on the command line). It may be worth doing another search for open-source sound stretchers in 2020. 

From your TODO list it looks like you have some cool plans lined up. I'm interested to see what you come up with! Just wanted to point I also did a (unfinished) [JS version of the pianoputer](https://github.com/Zulko/spinet), which makes for a better UX and allows the use of MIDI soundbanks.

**Comment by spacether** [comment]
Thanks for that clarification. Just now I submitted a PR from my branch
