### ISSUE TITLE
video effect when playing pianoputer

### ISSUE THREAD

**Issue by yoyoberenguer** [Zulko/pianoputer#19]
@Zulko @spacether  I made a version of pianoputer with an animated fire processed in real time. 
This is not essential, but with the graphic version, the window look a bit more appealing. 
The fire effect is base on a CYTHON algorithm that provide C performance to PYGAME and the animation will run on most computer over 100 fps (I am achieving a 200 FPS on mine).
The only downside would be the compilation of the CYTHON code for every version of python interpreter and CYTHON would be required in PYPI packages and added as a requirement in the project.
In the mean time, the easiest solution would be to build an executable file that will install pianoputer on window.

Just a suggestion, but if you are interested please check into https://github.com/yoyoberenguer/pianoputer 
Download the latest version ver 1.0.1 (exe) and watch a cosy fire

Kind Regards

**Comment by spacether** [comment]
Hey there. I tried running your version but it looks like it is missing the setup_project file:
```
(venv) justins-air:pianoputer justinblack$ python setup_project build_ext --inplace
/Users/justinblack/programming/scratch/pianoputer/venv/bin/python: can't open file 'setup_project': [Errno 2] No such file or directory
```
Am I doing something wrong? Could you include that file?
I am on macOs.

**Comment by yoyoberenguer** [comment]
Happy new year Justin,

I have place the file in the project. Feel free to try.
Kind Regards

Yoann

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by spacether** [comment]
Thanks for the suggestion. Let's leave it out as it would add a bit of complexity to the project.
