### ISSUE TITLE
Publishing to pypi

### ISSUE THREAD

**Issue by spacether** [Zulko/pianoputer#20]
@Zulko do you want to do it or do you want me to?
We have:
```
make testpypi
make pypi
```
in our Makefile to allow for easy publishing and the README.md will be used as the package description in pypi.

**Comment by spacether** [comment]
I didn't hear back so I published it with my account at https://pypi.org/project/pianoputer/
In pypi I invited you (Zulko) to also be an owner of the pianoputer package.

**Comment by Zulko** [comment]
Sorry for being slow and thanks for taking the initiative!

**Comment by spacether** [comment]
No worries; welcome :)
