### ISSUE TITLE
Cannot build/run from source 

### ISSUE THREAD

**Issue by yoyoberenguer** [Zulko/pianoputer#21]
Good day to you, 

Where do you find the package keyboardlayout  (no included in the source code)

I tried pip install keyboardlayout  but cannot find it anywhere (is it on Pypi?)

```
import keyboardlayout as kl
ModuleNotFoundError: No module named 'keyboardlayout'
```

Kind Regards

**Comment by spacether** [comment]
Hi there. Are you sure that your computer is connecting to pypi?
keyboardlayout is there at https://pypi.org/project/keyboardlayout/

**Comment by yoyoberenguer** [comment]
It works now with pip, no idea why it didn't worked in the first place. 
Thanks for you help, this can be close (human error)
Kind Regards
