### ISSUE TITLE
跪拜大佬牛年福星高照 (Kneel down to the big man, the year of the ox???)

### ISSUE THREAD

**Issue by huasheng-yue** [Zulko/pianoputer#25]
1）如何改善音质？
2）可否通过按键或者触控表现出乐音的强弱变化？

**Comment by spacether** [comment]
Translating this to English I get:
1) How to improve the sound quality?
Not sure how to improve this. Our audio files are transposed. Maybe switching to midi in the future would help? Sorry, I don;t have an answer here.
2) Is it possible to show the strength and weakness of the music through the keys or touch?
For this one I doubt that this is possible.
The only information that we have available is key press information.
So we lack any knowledge of how hard a key was pressed. We would need that knowledge to be able to make a sound louder or softer.
Does that answer your questions?

Translated back to Chinese:
1）如何提高音质？
不知道如何改善这一点。我们的音频文件已转置。也许将来改用Midi会有所帮助吗？抱歉，我没有答案。
2）是否可以通过按键或触摸来显示音乐的强弱？
对于这一点，我怀疑这是否可能。
我们唯一可用的信息是按键信息。
因此，我们对按键的按压程度一无所知。我们需要这些知识才能使声音响亮或柔和。
这能回答您的问题吗？

**Comment by spacether** [comment]
If I don't hear back on this in another week I will assume the message above answers your questions and close this ticket.
