### ISSUE TITLE
Harpsichord more than a PianoForte??

### ISSUE THREAD

**Issue by gustavklopp** [Zulko/pianoputer#5]
Hi
Very interesting project! But looking at your project, isn't it more of an Harpsichord than a piano that we are creating?
I mean, it doesn't seem to record the *speed* with which we are typing each key (which determine the loudness on a normal piano).
Would it be possible to take into account this type of information thanks to your program?

**Comment by Zulko** [comment]
No it is not possible. So yes, harpsichord or small electrical organ. I chose piano in the name because it speaks more.

**Comment by gustavklopp** [comment]
Thanks for your reply!
I wish they had realized their consumer product, begun in 2009 :/
https://www.youtube.com/watch?v=PDI8eYIASf0
